#file type
[[plugins]]
repo = 'Shougo/context_filetype.vim'

# denite
# [[plugins]]
# repo = 'Shougo/denite.nvim'
# on_cmd = 'Denite'
# depends = 'neomru.vim'
# hook_add = '''
#   source ~/.config/nvim/dein/plugins/denite-add.plug.vim
# '''
# hook_post_source = '''
#     source ~/.config/nvim/dein/plugins/denite-post.plug.vim
# '''

# [[plugins]]
# repo = 'Shougo/neomru.vim'

# [[plugins]]
# repo = 'Shougo/neoyank.vim'
# depends = 'denite.nvim'

# snippets, <C-n>で候補切り替え，候補を選択した状態で<C-k>でスニペット挿入，以後<C-k>で入力位置移動
[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_event = 'InsertCharPre'
on_ft = ['snippet']
depends = ['context_filetype.vim', 'neosnippet-snippets']
# depends = ['context_filetype.vim', 'neosnippet-snippets', 'honza/vim-snippets']
hook_source = '''
    source ~/.config/nvim/dein/plugins/neosnippet.plug.vim
'''

# echodoc
# [[plugins]]
# repo = 'Shougo/echodoc.vim'
# hook_add = '''
#   source ~/.config/nvim/dein/plugins/echodoc.plug.vim
# '''

# auto close
[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

# gitの操作
[[plugins]]
repo = 'tpope/vim-fugitive'

# gitの変更箇所を左側に表示する
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
    "変更箇所のハイライト
    let g:gitgutter_highlight_lines = 0
'''

# .コマンドでリピート可
[[plugins]]
repo = 'tpope/vim-repeat'

# html/CSS入力補助プラグイン
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['css', 'html', 'javascript', 'javascriptreact', 'javascript.jsx', 'typescript', 'typescriptreact', 'typescript.tsx']
hook_source = '''
    source ~/.config/nvim/dein/plugins/emmet-vim.plug.vim
'''

# tmuxline
[[plugins]]
repo = 'edkolev/tmuxline.vim'
 hook_source = '''
  source ~/.config/nvim/dein/plugins/tmuxline.plug.vim
 '''

# plugins for rust
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_add = '''
  let g:rustfmt_autosave = 1
'''

# precious
[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = 'context_filetype.vim'

# dart plugin
[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = 'dart'
hook_add = '''
  source ~/.config/nvim/dein/plugins/dart-vim-plugin.plug.vim
'''

# flutter plugin for neovim
[[plugins]]
repo = 'thosakwe/vim-flutter'
on_ft = 'dart'
hook_add = '''
  source ~/.config/nvim/dein/plugins/vim-flutter.plug.vim
'''

# save nvim session and restore nvim session
[[plugins]]
repo = 'tpope/vim-obsession'

# # javascript syntax
[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'javascriptreact', 'javascript.jsx']

# syntax plugins for javascript and javascript.jsx
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'javascriptreact', 'javascript.jsx']

# syntax plugins packages for javascript and javascript.jsx 
[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['javascript', 'javascriptreact', 'javascript.jsx']
depends = 'vim-javascript'

# syntax highlighting plugins for typescript
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript', 'typescriptreact', 'typescript.tsx']

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
on_ft = ['typescript', 'typescriptreact', 'typescript.tsx']
depends = 'typescript-vim'

# syntax highlighting plugin for styled-components
[[plugins]]
repo = 'styled-components/vim-styled-components'
on_ft = ['javascript','javascript.jsx', 'javascriptreact', 'typescript', 'typescript.tsx', 'typescriptreact', 'css', 'less', 'scss', 'json', 'graphql', 'markdown', 'vue', 'yaml', 'html']
hook_add = '''
  source ~/.config/nvim/dein/plugins/vim-styled-components.plug.vim
'''

# prettier for vim
# [[plugins]]
# repo = 'prettier/vim-prettier'
# rev = 'release/1.x'
# build = 'yarn install'
# on_ft = ['javascript','javascript.jsx', 'typescript', 'typescript.tsx', 'css', 'less', 'scss', 'json', 'graphql', 'markdown', 'vue', 'yaml', 'html']
# hook_add = '''
#   source ~/.config/nvim/dein/plugins/vim-prettier.plug.vim
# '''

# z.sh
[[plugins]]
repo = 'rupa/z'

# css-syntax
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['javascript','javascript.jsx', 'javascriptreact', 'typescript', 'typescript.tsx', 'typescriptreact', 'css', 'less', 'scss', 'json', 'graphql', 'markdown', 'vue', 'yaml', 'html']
