#file type
[[plugins]]
repo = 'Shougo/context_filetype.vim'

# denite
[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
depends = 'neomru.vim'
hook_add = '''
  source ~/.config/nvim/dein/plugins/denite-add.plug.vim
'''
hook_post_source = '''
    source ~/.config/nvim/dein/plugins/denite-post.plug.vim
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'
depends = 'denite.nvim'

# deoplete
[[plugins]]
repo = 'Shougo/deoplete.nvim'
build = ':UpdateRemotePlugins'
depends = 'context_filetype.vim'
on_event = 'InsertEnter'
hook_add = '''
    source ~/.config/nvim/dein/plugins/deoplete.plug.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_event = 'InsertCharPre'
on_ft = ['snippet']
depends = ['context_filetype.vim', 'neosnippet-snippets']
hook_source = '''
    source ~/.config/nvim/dein/plugins/neosnippet.plug.vim
'''

# auto close
[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

# gitの操作
[[plugins]]
repo = 'tpope/vim-fugitive'

# gitの変更箇所を左側に表示する
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
    "変更箇所のハイライト
    let g:gitgutter_highlight_lines = 0
'''

# .コマンドでリピート可
[[plugins]]
repo = 'tpope/vim-repeat'

#非同期コードチェッカー
[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
    source ~/.config/nvim/dein/plugins/ale.plug.vim
'''

# html/CSS入力補助プラグイン
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['css', 'html', 'javascript']
hook_source = '''
    source ~/.config/nvim/dein/plugins/emmet-vim.plug.vim
'''


# tmuxline
[[plugins]]
repo = 'edkolev/tmuxline.vim'
 hook_source = '''
  source ~/.config/nvim/dein/plugins/tmuxline.plug.vim
 '''

# 括弧の差し替え，追加，削除
[[plugins]]
repo = 'tpope/vim-surround'

# インデントライン
[[plugins]]
repo = 'Yggdroot/indentLine'

# plugins for rust
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_add = '''
  let g:rustfmt_autosave = 1
'''

# precious
[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = 'context_filetype.vim'

#fzf
 [[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0

#     " Prettierのパースエラーをquickfixに表示しない
#     let g:prettier#quickfix_enabled = 0

#     autocmd BufWritePre *.js,*.ts,*.jsx,*.vue,*.css,*.scss,*.json,*.md PrettierAsync
# "    source plugins/vim-prettier.plug
#     '''

# tmuxline
[[plugins]]
repo = 'edkolev/tmuxline.vim'
# hook_source = '''
  # let g:tmuxline_preset = {
    # \ 'a'  : '#S',
    # \ 'c'  : ['#(whoami)'],
    # \ 'win' : ['#I', '#W'],
    # \ 'cwin' : ['#I', '#W', '#F'],
    # \ 'x'  : ['#{battery_percentage} #{battery_icon}', '#{cpu_percentage} #{cpu_icon}'],
    # \ 'y'  : ['%a', '%R', '#(ansiweather -l Niigata-shi -w false -h false -p false -a false -s true | cut -d \" \" -f6,7,8,9)'],
    # \ 'z'  : '#H',
    # \ 'options'  : {'status-justify':'left'}}
  # let g:tmuxline_theme = 'angr'
# '''

# fzf.vim
[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
  source ~/.config/nvim/dein/plugins/fzf.plug.vim
  command! -bang -nargs=* Rg
    \ call fzf#vim#grep(
    \   'rg --line-number --no-heading '.shellescape(<q-args>), 0,
    \   fzf#vim#with_preview({'options': '--exact --reverse'}, 'right:50%:wrap'))
 '''
