# Required
[[plugins]]
repo = 'Shougo/dein.vim'

# snippets, <C-n>で候補切り替え，候補を選択した状態で<C-k>でスニペット挿入，以後<C-k>で入力位置移動
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# vim-airline
[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
  source ~/.config/nvim/dein/plugins/vim-airline.plug.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# airline theme 'angr'
[[plugins]]
repo = 'zacanger/angr.vim'

#vim color theme 'iceberg'
[[plugins]]
repo = 'cocopon/iceberg.vim'

#vim color theme 'hybrid'
[[plugins]]
repo = 'w0ng/vim-hybrid'

# vim-devicons
[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = '''
    " フォルダアイコンの表示をon
    let g:WebDevIconsUnicodeDecorateFolderNodes = 1
'''

# NERDTree, <C-n>で起動
[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

# yank履歴を遡る,ペースト後, ctrl+nで遡る,反対はctrl+p
[[plugins]]
repo = 'LeafCage/yankround.vim'
hook_add = '''
  source ~/.config/nvim/dein/plugins/yankround.plug.vim
'''
# Lnaguage Client
[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
hook_add = '''
   source ~/.config/nvim/dein/plugins/LanguageClient-neovim.plug.vim
'''

# コメント化，コメント解除，gc{motion}
[[plugins]]
repo = 'tpope/vim-commentary'

# defx vimfiler
# [[plugins]]
# repo = 'Shougo/defx.nvim'

