# Required
[[plugins]]
repo = 'Shougo/dein.vim'

# snippets
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# extra snippets
# [[plugins]]
# repo = 'honza/vim-snippets'

# vim-airline
[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
  source ~/.config/nvim/dein/plugins/vim-airline.plug.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# airline theme 'angr'
# [[plugins]]
# repo = 'zacanger/angr.vim'

#vim color theme 'iceberg'
# [[plugins]]
# repo = 'cocopon/iceberg.vim'

#vim color theme 'ondark'
# [[plugins]]
# repo = 'joshdick/onedark.vim'

#vim color theme 'one'
# [[plugins]]
# repo = 'rakr/vim-one'

#vim color theme 'neodark'
# [[plugins]]
# repo = 'KeitaNakamura/neodark.vim'

#vim color theme 'lucius'
# [[plugins]]
# repo = 'jonathanfilip/vim-lucius'

#vim color theme 'quantum'
[[plugins]]
repo = 'tyrannicaltoucan/vim-quantum'

#vim color theme 'hybrid'
# [[plugins]]
# repo = 'w0ng/vim-hybrid'

# vim-devicons
[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = '''
    " フォルダアイコンの表示をon
    let g:WebDevIconsUnicodeDecorateFolderNodes = 1
'''

# NERDTree, <C-n>で起動
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  " open a NERDTree automatically when vim starts up
  augroup nerdtree_config
    autocmd!
    autocmd vimenter * NERDTree
    autocmd vimenter * wincmd l
  " open a NERDTree automatically when vim starts up if no files were specified
  " autocmd StdinReadPre * let s:std_in=1
  " autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
  augroup END
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

# yank履歴を遡る,ペースト後, ctrl+nで遡る,反対はctrl+p
[[plugins]]
repo = 'LeafCage/yankround.vim'
hook_add = '''
  source ~/.config/nvim/dein/plugins/yankround.plug.vim
'''

# コメント化，コメント解除，gc{motion}
[[plugins]]
repo = 'tpope/vim-commentary'

# defx vimfiler
# [[plugins]]
# repo = 'Shougo/defx.nvim'

# 括弧の差し替え，追加，削除
[[plugins]]
repo = 'tpope/vim-surround'

# indent line
[[plugins]]
repo = 'Yggdroot/indentLine'

#fzf
[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

# fzf.vim
[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
  source ~/.config/nvim/dein/plugins/fzf.plug.vim
  command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   'rg --line-number --no-heading '.shellescape(<q-args>), 0,
  \   fzf#vim#with_preview({'options': '--exact --reverse'}, 'right:50%:wrap'))
'''

# shell interface for NeoVim
# [[plugins]]
# repo = 'Shougo/deol.nvim'

# float-preview
[[plugins]]
repo = 'ncm2/float-preview.nvim'
hook_add = '''
  source ~/.config/nvim/dein/plugins/float-preview.plug.vim
'''

# move (), {}, tag and etc...
[[plugins]]
repo = 'andymass/vim-matchup'
