#file type
[[plugins]]
repo = 'Shougo/context_filetype.vim'

# denite
[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
depends = 'neomru.vim'
hook_add = '''
  source ~/.config/nvim/dein/plugins/denite-add.plug.vim
'''
hook_post_source = '''
    source ~/.config/nvim/dein/plugins/denite-post.plug.vim
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'
depends = 'denite.nvim'

# deoplete
[[plugins]]
repo = 'Shougo/deoplete.nvim'
build = ':UpdateRemotePlugins'
depends = 'context_filetype.vim'
on_event = 'InsertEnter'
hook_add = '''
    source ~/.config/nvim/dein/plugins/deoplete.plug.vim
'''

# snippets, <C-n>で候補切り替え，候補を選択した状態で<C-k>でスニペット挿入，以後<C-k>で入力位置移動
[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_event = 'InsertCharPre'
on_ft = ['snippet']
depends = ['context_filetype.vim', 'neosnippet-snippets']
# depends = ['context_filetype.vim', 'neosnippet-snippets', 'honza/vim-snippets']
hook_source = '''
    source ~/.config/nvim/dein/plugins/neosnippet.plug.vim
'''

# auto close
[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

# gitの操作
[[plugins]]
repo = 'tpope/vim-fugitive'

# gitの変更箇所を左側に表示する
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
    "変更箇所のハイライト
    let g:gitgutter_highlight_lines = 0
'''

# .コマンドでリピート可
[[plugins]]
repo = 'tpope/vim-repeat'

#非同期コードチェッカー
# [[plugins]]
# repo = 'w0rp/ale'
# hook_add = '''
#     source ~/.config/nvim/dein/plugins/ale.plug.vim
# '''

# html/CSS入力補助プラグイン
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['css', 'html', 'javascript', 'javascript.jsx']
hook_source = '''
    source ~/.config/nvim/dein/plugins/emmet-vim.plug.vim
'''


# tmuxline
[[plugins]]
repo = 'edkolev/tmuxline.vim'
 hook_source = '''
  source ~/.config/nvim/dein/plugins/tmuxline.plug.vim
 '''

# 括弧の差し替え，追加，削除
# [[plugins]]
# repo = 'tpope/vim-surround'

# インデントライン
# [[plugins]]
# repo = 'Yggdroot/indentLine'

# plugins for rust
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_add = '''
  let g:rustfmt_autosave = 1
'''

# precious
[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = 'context_filetype.vim'

#fzf
 [[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0

# fzf.vim
[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
  source ~/.config/nvim/dein/plugins/fzf.plug.vim
  command! -bang -nargs=* Rg
    \ call fzf#vim#grep(
    \   'rg --line-number --no-heading '.shellescape(<q-args>), 0,
    \   fzf#vim#with_preview({'options': '--exact --reverse'}, 'right:50%:wrap'))
 '''

# julia plugins
# [[plugins]]
# repo = 'JuliaEditorSupport/julia-vim'
# on_ft = 'julia'
# hook_add = '''
  # source ~/.config/nvim/dein/plugins/julia-vim.plug.vim
# '''

# matlab plugin
# [[plugins]]
# repo = 'MortenStabenau/matlab-vim'
# on_ft = 'matlab'
# hook_add = '''
#   let g:matlab_panel_size = 50
# '''

# dart plugin
[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = 'dart'
hook_add = '''
  source ~/.config/nvim/dein/plugins/dart-vim-plugin.plug.vim
'''

# flutter plugin for neovim
[[plugins]]
repo = 'thosakwe/vim-flutter'
on_ft = 'dart'
hook_add = '''
  source ~/.config/nvim/dein/plugins/vim-flutter.plug.vim
'''

# save nvim session and restore nvim session
[[plugins]]
repo = 'tpope/vim-obsession'

# vim quickrun
# [[plugins]]
# repo = 'thinca/vim-quickrun'
# hook_add = '''
#   source ~/.config/nvim/dein/plugins/vim-quickrun.plug.vim
# '''

# function signature
# [[plugins]]
# repo = 'Shougo/echodoc.vim'
# hook_add = '''
#   source ~/.config/nvim/dein/plugins/echodoc.plug.vim
# '''

# syntax plugins for javascript and javascript.jsx
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'typescript']

# syntax plugins packages for javascript and javascript.jsx 
# [[plugins]]
# repo = 'mxw/vim-jsx'
# on_ft = ['javascript', 'javascript.jsx']
# depends = 'vim-javascript'

# syntax plugins for typescript
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

# syntax plugin for typescript jsx
[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
on_ft = ['typescript', 'javascript']
hook_add = '''
  let g:vim_jsx_pretty_highlight_close_tag = 1
  let g:vim_jsx_pretty_colorful_config = 1
'''

# Lnaguage Client
[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
on_ft = ['rust', 'dart', 'python', 'sh']
build = 'bash install.sh'
hook_add = '''
   source ~/.config/nvim/dein/plugins/LanguageClient-neovim.plug.vim
'''

# auto linter and fixer
[[plugins]]
repo = 'dense-analysis/ale'
on_ft = ['javascript', 'typescript']
hook_add = '''
  source ~/.config/nvim/dein/plugins/ale.plug.vim
'''

# tagbar
[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
  nnoremap <silent> m :TagbarToggle<CR>
'''

# float-preview
# [[plugins]]
# repo = 'ncm2/float-preview.nvim'
# hook_add = '''
#   source ~/.config/nvim/dein/plugins/float-preview.plug.vim
# '''
